apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-app
  labels:
    app: wil42-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-app
  template:
    metadata:
      labels:
        app: wil42-app
    spec:
      containers:
      - name: wil42-app
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: wil42-service
spec:
  selector:
    app: wil42-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-ingress
#   namespace: dev
# spec:
#   ingressClassName: traefik
#   rules:
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: wil42-service
#             port:
#               number: 8888