apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-app
  labels:
    app: wil42-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-app
  template:
    metadata:
      labels:
        app: wil42-app
    spec:
      containers:
      - name: wil42-app
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: wil42-service
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: wil42-app